### PR TITLE
Support runtime options

### PR DESCRIPTION
**Pull request by jjcarstens**
The previous release made a breaking change which ended up being the wrong
choice and broke more things than it helped. Instead, this reverts those
strict conditions and is backwards compatible.

It fixes support for using `runtime.exs` and allows multitenant settings
through the `Ueberauth.Strategy.Okta.OAuth` scope in the application
config

/cc @mustela

### CODE REVIEW

**Comment by mustela** [comment]
Hmm doesn't seems to be working added the branch in [here](https://github.com/mustela/okta-test/commit/30cc3fd79bffa40c1e7688a28c6e63b1ab47f0c6)

**Comment by mustela** [comment]
@jjcarstens I was checking other services I have with ueberauth and this is how Im [configuring it](https://github.com/livesup-dev/livesup/blob/main/config/config.exs#L75). Wondering if we should take that approach instead of adding this runtime feature.

**Comment by jjcarstens** [comment]
Correct, with your settings, `config.exs` is evaluated at compile time. So adding the System env var calls there would require you to specify them when building the release (i.e. `OKTA_CLIENT_SECRET=1234 mix release`)

Using `runtime.exs` would require you to supply the env vars when you are running the release executable (which is what your sample lib is doing)

The problem with the how you're [configuring it](https://github.com/livesup-dev/livesup/blob/main/config/config.exs#L75) is it does not support multi tenancy with different credentials for different providers. We could go that route and keep using the `Ueberauth.Strategy.Okta.OAuth` key with a `:providers` key as well, but thats just slightly annoying since it already exists at the Ueberauth level which already does resolving there.

Using the `:runtimes_options`, allows you to make a callback and do whatever you want (Lookup values in `Application`, provide your own provider resolving, make `System.get_env` calls, etc). If its not quite hitting home, I can adjust. Just need to time to think on it 🤔

**Comment by jjcarstens** [comment]
Ok @mustela, I totally reworked this. The old way of configuring should still work and it also supports the multitenant case as well. Can you give this a try with your setup when you have a second?

**Pull request merged**
